default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 5819Lincoln@
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: appointments_app_development
test:
  <<: *default
  database: appointments_app_test


production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>